// Mande Icon Organizer — Figma Plugin
// Scans components on the current page, groups them by icon name,
// and reorganises them into Component Sets with Size + Style variant properties.
// Missing sizes are auto-generated by scaling the closest existing size.

const VALID_SIZES = [16, 20, 24, 32];
const VALID_STYLES = ["Filled", "Outlined"];

figma.showUI(__html__, { width: 440, height: 600, title: "Mande Icon Organizer" });

// ─── Message router ───────────────────────────────────────────────────────────

figma.ui.onmessage = async function (msg) {
  switch (msg.type) {
    case "scan":
      handleScan(msg.separator);
      break;
    case "organize":
      await handleOrganize(msg.groups, msg.separator);
      break;
    case "close":
      figma.closePlugin();
      break;
  }
};

// ─── Scan ─────────────────────────────────────────────────────────────────────

function handleScan(separator) {
  separator = separator || "/";

  const components = figma.currentPage.findAllWithCriteria({
    types: ["COMPONENT"],
  });

  const groupMap = {};
  const unmatched = [];

  for (const comp of components) {
    const parsed = parseName(comp.name, separator);
    if (parsed) {
      if (!groupMap[parsed.baseName]) {
        groupMap[parsed.baseName] = { baseName: parsed.baseName, variants: [] };
      }
      groupMap[parsed.baseName].variants.push({
        id: comp.id,
        name: comp.name,
        size: parsed.size,
        style: parsed.style,
        width: Math.round(comp.width),
        height: Math.round(comp.height),
      });
    } else {
      unmatched.push({ id: comp.id, name: comp.name });
    }
  }

  // Compute which sizes will be generated (existing + scaled)
  const groupsWithPreview = Object.values(groupMap).map(function (g) {
    const styleMap = buildStyleMap(g.variants);
    const styles = Object.keys(styleMap);
    const totalVariants = styles.length * VALID_SIZES.length;
    const existingVariants = g.variants.length;
    return Object.assign({}, g, {
      totalVariants: totalVariants,
      scaledCount: totalVariants - existingVariants,
      styles: styles,
    });
  });

  figma.ui.postMessage({
    type: "scan-result",
    groups: groupsWithPreview,
    unmatched: unmatched,
    total: components.length,
  });
}

// ─── Name parser ──────────────────────────────────────────────────────────────
// Supports any ordering: "Arrow Right/Filled/16", "16/Arrow Right/Outlined", etc.

function parseName(name, separator) {
  const parts = name.split(separator).map(function (s) { return s.trim(); });
  if (parts.length < 2) return null;

  var baseName = null, size = null, style = null;

  for (var i = 0; i < parts.length; i++) {
    var part = parts[i];
    var num = parseInt(part, 10);

    if (VALID_SIZES.indexOf(num) !== -1 && String(num) === part.trim()) {
      size = num;
    } else if (VALID_STYLES.map(function (s) { return s.toLowerCase(); }).indexOf(part.toLowerCase()) !== -1) {
      style = part.charAt(0).toUpperCase() + part.slice(1).toLowerCase();
    } else {
      if (baseName === null) baseName = part;
    }
  }

  if (!baseName) return null;
  return { baseName: baseName, size: size, style: style };
}

// ─── Style map helper ─────────────────────────────────────────────────────────
// Returns { "Filled": { 16: nodeId, 20: nodeId }, "Outlined": { 20: nodeId } }

function buildStyleMap(variants) {
  var styleMap = {};
  for (var i = 0; i < variants.length; i++) {
    var v = variants[i];
    var style = v.style || "Outlined";
    var size  = v.size  || 20;
    if (!styleMap[style]) styleMap[style] = {};
    styleMap[style][size] = v.id;
  }
  return styleMap;
}

// ─── Closest size finder ──────────────────────────────────────────────────────

function findClosestSize(existingSizes, target) {
  return existingSizes.reduce(function (closest, s) {
    return Math.abs(s - target) < Math.abs(closest - target) ? s : closest;
  });
}

// ─── Organise ─────────────────────────────────────────────────────────────────

async function handleOrganize(groups, separator) {
  try {
    await figma.loadFontAsync({ family: "Inter", style: "Regular" });
    await figma.loadFontAsync({ family: "Inter", style: "Medium" });
  } catch (_) {}

  const page = figma.currentPage;

  // Wrapper frame with wrap auto-layout
  const wrapper = figma.createFrame();
  wrapper.name = "Icons / Organised";
  wrapper.layoutMode = "HORIZONTAL";
  wrapper.layoutWrap = "WRAP";
  wrapper.itemSpacing = 80;
  wrapper.counterAxisSpacing = 100;
  wrapper.paddingTop = 48;
  wrapper.paddingBottom = 48;
  wrapper.paddingLeft = 48;
  wrapper.paddingRight = 48;
  wrapper.fills = [{ type: "SOLID", color: { r: 0.98, g: 0.98, b: 0.98 } }];
  wrapper.primaryAxisSizingMode = "FIXED";
  wrapper.counterAxisSizingMode = "HUG";
  wrapper.resize(1440, 200);

  // Place below all existing content
  var maxY = 0;
  page.children.forEach(function (n) {
    if (n.y + n.height > maxY) maxY = n.y + n.height;
  });
  wrapper.y = maxY + 80;
  wrapper.x = 0;
  page.appendChild(wrapper);

  var organised = 0, skipped = 0;

  for (var i = 0; i < groups.length; i++) {
    var result = await buildComponentSet(groups[i], page, wrapper);
    if (result) organised++;
    else skipped++;
  }

  figma.viewport.scrollAndZoomIntoView([wrapper]);

  figma.ui.postMessage({
    type: "organize-done",
    organised: organised,
    skipped: skipped,
  });
}

// ─── Build one Component Set ──────────────────────────────────────────────────
// For each style that exists, generates all 4 sizes by scaling if needed.

async function buildComponentSet(group, page, wrapper) {
  if (!group.variants || group.variants.length === 0) return false;

  const styleMap = buildStyleMap(group.variants);
  const styles = Object.keys(styleMap);
  if (styles.length === 0) return false;

  const allVariants = [];

  for (var si = 0; si < styles.length; si++) {
    var style = styles[si];
    var sizeMap = styleMap[style];
    var existingSizes = Object.keys(sizeMap).map(Number);

    for (var vi = 0; vi < VALID_SIZES.length; vi++) {
      var targetSize = VALID_SIZES[vi];
      var clone;

      if (sizeMap[targetSize]) {
        // Exact match — clone as-is
        var exactNode = figma.getNodeById(sizeMap[targetSize]);
        if (!exactNode || exactNode.type !== "COMPONENT") continue;
        clone = exactNode.clone();
        page.appendChild(clone);
      } else {
        // Scale from the 24px icon (canonical 2px-stroke source).
        // Fall back to closest size if 24px isn't available.
        var sourceSize = sizeMap[24] ? 24 : findClosestSize(existingSizes, targetSize);
        var sourceNode = figma.getNodeById(sizeMap[sourceSize]);
        if (!sourceNode || sourceNode.type !== "COMPONENT") continue;

        clone = sourceNode.clone();
        page.appendChild(clone);

        // rescale() scales the frame + all children + strokes proportionally
        var scale = targetSize / sourceSize;
        clone.rescale(scale);
      }

      clone.name = "Size=" + targetSize + ", Style=" + style;
      allVariants.push(clone);
    }
  }

  if (allVariants.length === 0) return false;

  var set = figma.combineAsVariants(allVariants, page);
  set.name = group.baseName;
  wrapper.appendChild(set);

  return true;
}
